### ISSUE TITLE
Process button is not responding in creating new Transaction and new Donor Commitment

### ISSUE THREAD

**Issue by peydelavega** [microsoft/fundraising-and-engagement#4] opened 2020-10-26 06:14 UTC
I have a trial environment with Fundraising and Events Accelerator. I'm trying to add new Transaction and new Donor Commitment for a contact but the Process button is not responding, and when I try to Save, it gives me this error: "Clicking Save or Save and Close will not process a transaction. Selecting Process is the only way to complete a Donor Commitment"

![ProcessButton](https://user-images.githubusercontent.com/73459736/97139474-8c84a000-1795-11eb-84e5-9b201f55f859.png)

**Comment by savaaran** [comment] 2020-10-27 08:48
Hi,
This issue is likely caused by

1) not having a Configuration record associated with your user account
2) not having a PaymentProcessor defined in the Configuration record

The configuration settings are accessed through the Configuration section in the Fundraising and Engagement application. We will update the documentation detailing on how to set up the Configuration record with the PaymentProcessor.

**Comment by peydelavega** [comment] 2020-10-29 06:35
User account has been set up to the Primary Configuration Record and a Payment Processor has also been assigned.
Tried to add new Transaction again and this time there's a an error to the Process button, it says: 

"An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  Plugins.TransactionGiftCreate: System.Exception: The remote server returned an error: (401) Unauthorized."

![image](https://user-images.githubusercontent.com/73459736/97533498-4298f580-19f3-11eb-8d67-43bdc2481f0e.png)
![image](https://user-images.githubusercontent.com/73459736/97533626-84c23700-19f3-11eb-8ab1-231e9fea9132.png)
![image](https://user-images.githubusercontent.com/73459736/97533883-031ed900-19f4-11eb-92ed-f380a44fe835.png)

**Comment by klbyrd** [comment] 2020-10-29 14:07
Hi @peydelavega, thank you for your question. Can you please submit a support case [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwPOUgp66fBDqJRPHc2w2lhUNzI1SDgxRjY2VU5GT0EzSkEzMzU1Q1I3WCQlQCN0PWcu)? Our team will be able to help you troubleshoot better through the support process. Thank you!

**Comment by klbyrd** [comment] 2020-10-30 20:03
Resolved via support process

**Closed** 2020-10-30 20:03 UTC
